### ISSUE TITLE
Support NEO-GEO games with multiple rom files

### ISSUE THREAD

**Issue by MajorDangerNine** [sigboe/pie-galaxy#6]
The following Neo Geo ROMs fail to install from their respective Linux game installers:

- kof2000 - King of Fighters 2000
- kof2002 - King of Fighters 2002
- samsh5sp - Samurai Shodown V Special

Problem possibly due to presence of the following additional ROMs:

- kof2000n - King of Fighters 2000, The (Non-Encrypted P)
- kof2k2nd - King of Fighters 2002, The (Decrypted C)
- ss5shnd - Samurai Shodown V Special (Decrypted C)

**Comment by sigboe** [comment]
will any of these roms work without conversion if you copy files manually?

**Comment by MajorDangerNine** [comment]
**Works As Is**

- kof2000 - King of Fighters 2000
- kof2002 - King of Fighters 2002
- kof2000n - King of Fighters 2000, The (Non-Encrypted P)
- samsh5sp - Samurai Shodown V Special

**Conversion Needed**

- ss5shnd - Samurai Shodown V Special (Decrypted C) - Makes samsh5sph and samsh5spho.

**Unusable**

- kof2k2nd - King of Fighters 2002, The (Decrypted C)

**Comment by sigboe** [comment]
This should be fixed via this commit bbe513231a2aba7298e4e4c37670a5cfc67a8fa1
Can you test now?

**Comment by MajorDangerNine** [comment]
Fixed
