### ISSUE TITLE
wyvern download gives a 404 html page on ARM

### ISSUE THREAD

**Issue by timfel** [sigboe/pie-galaxy#7]
The download for ARM seems to be broken. I guess it might make sense to host binaries with this project

**Comment by nicohman** [comment]
Woops--that was my bad. Switched to a new server last night and didn't get the arm build in the transfer. Should be fixed now.

**Comment by sigboe** [comment]
@nicohman Did you put the new version with ability to download specific extras, and without downloading using a search term for the game name?

**Comment by nicohman** [comment]
Thanks for reminding me; I'll start building that now and let you know when it's been updated.

**Comment by nicohman** [comment]
@sigboe All set up with the most recent version. I changed the link to [this](https://demenses.net/wyvern-arm-nightly) to reflect that it should now be updated much more frequently--I set up cross-compiling. Let me know if you have any issues--I tested it on my pi, so it should work, but it was all quite fiddly, so there could be something wrong with the binary or something.

**Comment by sigboe** [comment]
@nicohman nice, a static url that doesn't need update :)
Is it actually nightly now? Buildbot?

**Comment by nicohman** [comment]
Should be automated once I finish setting it up—for now, I just threw up a manually compiled binary for speed. I’ll see if I can make a manifest for that tonight.
